blogName: Darky's Blog
authorName: darkyzhou
url: https://darkyzhou.net
description: 别把看重的东西附上无边的价值
dir: ltr
language: zh-CN
analytics:
  baiduId: f60a9a2b48d8e5dd35145c273edec8ef
  gaMeasurementId: UA-169813168-1
comments:
  - type: utterances
    repository: darkyzhou/blog
    issueTerm: title
    label: ""
    theme: github-dark
  - type: none
